# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 09:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supportchat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatsession',
            options={'permissions': (('can_chat', 'Can access and manage support chats'),)},
        ),
    ]
